filesToProcess:
  - /Users/nicklittlefield/PycharmProjects/eye-tracking-preprocessing/data/2538 40 41 42 43.csv
  - /Users/nicklittlefield/PycharmProjects/eye-tracking-preprocessing/data/version 1a.csv
  - /Users/nicklittlefield/PycharmProjects/eye-tracking-preprocessing/data/version 5a.tsv
  - /Users/nicklittlefield/PycharmProjects/eye-tracking-preprocessing/data/version 8b.tsv

outdir: data/
columnsToKeep:
  - Participant name
  - Recording name
  - Recording timestamp
  - Presented Stimulus name
  - Pupil diameter left
  - Pupil diameter right
  - AOI hit [Box:Bottom]
  - AOI hit [Box:Top]
  - Eye movement type
columnsForPupil:
  - Participant name
  - Recording name
  - Presented Stimulus name
  - Recording timestamp
  - Pupil diameter left
  - Pupil diameter right
columnsForAOI:
  - Participant name
  - Recording name
  - Recording timestamp
  - Presented Stimulus name
  - AOI hit [Box:Bottom]
  - AOI hit [Box:Top]
invalidEyeMovements:
  - EyesNotFound
stimulusNameFilter: ^[1][ a-zA-Z0-9]*
pupilThreshold: 0.5
